
# Site configuration

targets:
    - name:         "desktop"
      description:  "Desktop or tablet"

sites:
    - name:         "e-bike"
      description:  "E-Bike Selector"

languages:
    - name:         "nl"
      description:  "Dutch"
      locale:       "nl_NL.utf-8"


routeprefixes:
    - filter:       { target: "desktop", site: "e-bike", language: "nl" }
      prefix:       "http://e-bike.twokings.eu/"

routes:
    - filter:       { target: "desktop", site: "e-bike", language: false }
      pattern:      ""
      public:       ""
      defaults:     { _rewrite: "_page/about" }

    - filter:       { target: "desktop", site: "e-bike", language: false }
      pattern:      "_page/about"
      public:       "over"
      defaults:     { _controller: "TwoKingsEBikeBundle:Default:showAbout" }

    - filter:       { target: "desktop", site: "e-bike", language: false }
      pattern:      "_banner/{width}x{height}"
      public:       "banner/{width}x{height}"
      defaults:     { _controller: "TwoKingsEBikeBundle:Default:showBanner" }
      requirements:
          width:    "[0-9]+"
          height:   "[0-9]+"

    - filter:       { target: "desktop", site: "e-bike", language: false }
      pattern:      "bike/results"
      public:       "fietsen"
      defaults:     { _controller: "TwoKingsEBikeBundle:Default:showResults" }

    - filter:       { target: "desktop", site: "e-bike", language: false }
      pattern:      "bike/{publicid}"
      public:       "fietsen/{publicid}"
      defaults:     { _controller: "TwoKingsEBikeBundle:Default:showBike" }
      requirements:
          publicid: "[a-z0-9-]+"

