TwoKingsEBikeBundle:
    resource: "@TwoKingsEBikeBundle/Resources/config/routing.yml"
    prefix:   /

PivotXMiscBundle:
    resource: "@MiscBundle/Controller/"
    type:     annotation
    prefix:   /

PivotXBackendBundle:
    resource: "@BackendBundle/Resources/config/routing.php"
    prefix:   /pivotx

PivotXCoreBundle:
    resource: "@CoreBundle/Resources/config/routing.php"
    prefix:   /pivotx_core

# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
