<?php

namespace PivotX\CoreBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ExtrafieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExtrafieldRepository extends EntityRepository
{
}