TwoKings\Bundle\EBikeBundle\Entity\Bike:
  type: entity
  table: bike
  repositoryClass: TwoKings\Bundle\EBikeBundle\Model\BikeRepository
  fields:
    id:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      id: true
      generator:
        strategy: IDENTITY
    publicid:
      type: string
      length: 64
      precision: 0
      scale: 0
      nullable: true
      unique: false
    date_created:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        timestampable:
          on: create
    date_modified:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        timestampable:
          on: update
    viewable:
      type: boolean
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    title:
      type: string
      length: 255
      precision: 0
      scale: 0
      nullable: false
      unique: false
    no_of_reviews:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    review_rating:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    available:
      type: boolean
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    price:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    weight:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    weight_battery:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    year_built:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    range_min:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    range_avg:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    range_max:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    battery_voltage:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    battery_amps:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    engine_location:
      type: string
      length: 255
      precision: 0
      scale: 0
      nullable: false
      unique: false
    image_file:
      type: string
      length: 255
      precision: 0
      scale: 0
      nullable: false
      unique: false
    brochure_file:
      type: string
      length: 255
      precision: 0
      scale: 0
      nullable: false
      unique: false
    product_uri:
      type: string
      length: 255
      precision: 0
      scale: 0
      nullable: false
      unique: false
    info:
      type: text
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
  oneToMany:
    reviews:
      targetEntity: BikeReview
      cascade:
        - remove
      mappedBy: bike
      inversedBy: null
      orphanRemoval: true
      orderBy: null
  manyToOne:
    brand:
      targetEntity: Brand
      cascade: {  }
      mappedBy: null
      inversedBy: bikes
      joinColumns:
        brand_id:
          referencedColumnName: id
      orphanRemoval: false
  lifecycleCallbacks: {  }
