TwoKings\Bundle\EBikeBundle\Entity\Page:
  type: entity
  table: page
  repositoryClass: TwoKings\Bundle\EBikeBundle\Model\PageRepository
  fields:
    id:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      id: true
      generator:
        strategy: IDENTITY
    publicid:
      type: string
      length: 64
      precision: 0
      scale: 0
      nullable: true
      unique: true
    date_created:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        timestampable:
          on: create
    date_modified:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        timestampable:
          on: update
    viewable:
      type: integer
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
    publish_state:
      type: string
      length: 32
      precision: 0
      scale: 0
      nullable: false
      unique: false
      auto_entity:
        publishable:
          type: state
    publish_on:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: true
      unique: false
      auto_entity:
        publishable:
          type: publish
    depublish_on:
      type: datetime
      length: null
      precision: 0
      scale: 0
      nullable: true
      unique: false
      auto_entity:
        publishable:
          type: depublish
    title:
      type: string
      length: 255
      precision: 0
      scale: 0
      nullable: false
      unique: false
    body:
      type: text
      length: null
      precision: 0
      scale: 0
      nullable: false
      unique: false
  lifecycleCallbacks: {  }
